a6p1A: Assign06P1A.o Assign06P1A.cpp
	g++ Assign06P1A.o -o a6p1A
Assign06P1A.o: Assign06P1A.cpp
	g++ -Wall -ansi -pedantic -std=c++11 -c Assign06P1A.cpp

go:
	./a6p1A
gogo:
	./a6p1A > a6p1Atest.out
nt:
	@rm -rf a6p1A a6p1A.o a6p1Atest.out
clean:
	@rm -rf a6p1A.o
cleanall:
	@rm -rf a6p1A.o a6p1A
